---
version: "2"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: false
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
- node_modules/**/*
- server/tests/**/*
- client/**/*
- coverage/**/*