language: node_js
node_js:
- "stable"
env:
- NODE_ENV=test
cache:
 directories:
 - node_modules
addons:
- postgresql: "9.4"
services:
- postgresql
before_script:
- psql -c 'create database test;' -U postgres
- psql -c "CREATE USER Davitron WITH PASSWORD 'postgres';" -U postgres
- npm install
- sequelize db:migrate && sequelize db:seed:all
script:
- npm test
- npm run coverage
after_success: 'npm run coveralls'
 