language: node_js
node_js:
- "9.11.1"
env:
- NODE_ENV=test
cache:
 directories:
 - node_modules
addons:
- postgresql: "9.4"
services:
- postgresql
before_script:
- npm -g install codecov
- npm install
- psql -c 'create database test;' -U postgres
- sequelize db:migrate && sequelize db:seed:all
script:
- npm run full-test
- npm run coverage
after_success:
- 'npm run coveralls'
 