language: node_js
node_js:
- "stable"
env:
- NODE_ENV=development
cache:
 directories:
 - node_modules
addons:
- postgresql: "9.4"
services:
- postgresql
before_script:
- psql -c 'create database eventManagerDTO;' -U postgres
- npm install
- sequelize db:migrate && sequelize db:seed
script:
- npm test
- npm run coverage
after_success: 'npm run coveralls'
 