language: node_js
node_js:
- "stable"
env:
- NODE_ENV=development
cache:
 directories:
 - node_modules
addons:
- postgresql: "9.4"
services:
- postgresql
before_script:
- psql -c 'create database eventManager-DTO;' -U postgres
script:
- npm test
- npm run coverage
- npm install
after_success: 'npm run coveralls'
 