language: node_js
node_js:
- "stable"
env:
# global:
#   - export NODE_ENV=development
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
- npm test
- npm run coverage
- npm install
after_success: 'npm run coveralls'
 