const centerActionType = {
  CREATE_REQUEST: 'CENTER_CREATE_REQUEST',
  CREATE_SUCCESS: 'CENTER_CREATE_SUCCESS',
  CREATE_FAILED: 'CENTER_CREATE_FAILED',

  GETALL_REQUEST: 'CENTER_GETALL_REQUEST',
  GETALL_SUCCESS: 'CREATE_GETALL_SUCCESS',
  GETALL_FAILED: 'CENTER_GETALL_FAILED',

  GET_REQUEST: 'CENTER_GET_REQUEST',
  GET_SUCCESS: 'CREATE_GET_SUCCESS',
  GET_FAILED: 'CENTER_GET_FAILED',

  GETSTATES_REQUEST: 'STATES_GET_REQUEST',
  GETSTATES_SUCCESS: 'STATES_GET_SUCCESS',
  GETSTATES_FAILED: 'STATES_GET_FAILED',

  UPDATE_REQUEST: 'CENTER_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'CREATE_UPDATE_SUCCESS',
  UPDATE_FAILED: 'CENTER_UPDATE_FAILED',

  DELETE_REQUEST: 'CENTER_DELETE_REQUEST',
  DELETE_SUCCESS: 'CREATE_DELETE_SUCCESS',
  DELETE_FAILED: 'CENTER_DELETE_FAILED',
};

export default centerActionType;
